on:
  push:
    branches:
      - master
    paths:
      - profile.json

jobs:
  sync-profile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises
            const profile = JSON.parse(await fs.readFile('./profile.json'))
            await github.users.updateAuthenticated(profile.user)